import bcrypt from 'bcryptjs';
import {
  User,
  Category,
  Product,
  Coupon,
  Banner,
  StoreSettings,
  Review,
  Order,
} from '../types.ts';

const salt = bcrypt.genSaltSync(10);
const adminPasswordHash = bcrypt.hashSync('AdminPassword123!', salt);
const customerPasswordHash = bcrypt.hashSync('Customer123!', salt);

export const initialUsers: User[] = [
  {
    id: 'usr_admin_1',
    name: 'Baggio Administrator',
    email: 'admin@baggio.com',
    passwordHash: adminPasswordHash,
    phone: '+1 (555) 987-6543',
    role: 'admin',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'usr_cust_1',
    name: 'Alexander Rossi',
    email: 'customer@baggio.com',
    passwordHash: customerPasswordHash,
    phone: '+1 (555) 234-5678',
    role: 'customer',
    status: 'active',
    createdAt: '2026-01-10T14:30:00.000Z',
    updatedAt: '2026-01-10T14:30:00.000Z',
  },
  {
    id: 'usr_cust_2',
    name: 'Sophia Laurent',
    email: 'sophia.laurent@example.com',
    passwordHash: customerPasswordHash,
    phone: '+1 (555) 876-5432',
    role: 'customer',
    status: 'active',
    createdAt: '2026-02-15T09:12:00.000Z',
    updatedAt: '2026-02-15T09:12:00.000Z',
  },
];

export const initialCategories: Category[] = [
  {
    id: 'cat_leather',
    name: 'Leather Goods',
    slug: 'leather-goods',
    description: 'Mastercrafted Tuscan full-grain leather bags, briefcases, and carryalls designed for longevity.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_timepieces',
    name: 'Luxury Timepieces',
    slug: 'luxury-timepieces',
    description: 'Precision mechanical chronographs and minimalist dress watches engineered with Swiss movements.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_footwear',
    name: 'Artisanal Footwear',
    slug: 'artisanal-footwear',
    description: 'Blake-stitched Italian leather oxfords, suede chelsea boots, and refined minimalist court sneakers.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_apparel',
    name: 'Tailored Apparel',
    slug: 'tailored-apparel',
    description: 'Timeless outerwear, pure Mongolian cashmere knitwear, and structured silhouettes in natural fibers.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat_accessories',
    name: 'Eyewear & Accessories',
    slug: 'eyewear-accessories',
    description: 'Handcrafted acetate sunglasses, woven silk ties, and brass cuff hardware.',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop',
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'The Verona Executive Leather Briefcase',
    slug: 'verona-executive-leather-briefcase',
    sku: 'BG-LEA-001',
    description:
      'Forged from vegetable-tanned full-grain Florentine calfskin, the Verona Briefcase blends boardroom refinement with daily utility. Features dual accordion compartments, a padded 16-inch laptop pocket, polished solid brass buckle closures, and a detachable padded shoulder strap. Over time, the leather develops an irreplaceable, deep patina that tells your story.',
    shortDescription: 'Hand-burnished full-grain Italian leather briefcase with brass hardware.',
    categoryId: 'cat_leather',
    brand: 'Baggio Atelier',
    regularPrice: 480,
    salePrice: 420,
    costPrice: 190,
    tax: 8.5,
    discount: 12.5,
    stockQuantity: 28,
    lowStockThreshold: 5,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_1_1',
        url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_1_2',
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
      {
        id: 'img_1_3',
        url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 3,
      },
    ],
    variants: [
      {
        id: 'var_1_1',
        name: 'Cognac Brown / Standard',
        sku: 'BG-LEA-001-COG',
        color: 'Cognac Brown',
        size: 'One Size',
        price: 420,
        stockQuantity: 16,
      },
      {
        id: 'var_1_2',
        name: 'Midnight Noir / Standard',
        sku: 'BG-LEA-001-BLK',
        color: 'Midnight Noir',
        size: 'One Size',
        price: 420,
        stockQuantity: 12,
      },
    ],
    weight: 1.8,
    length: 42,
    width: 12,
    height: 31,
    seoTitle: 'Verona Executive Leather Briefcase | Baggio',
    seoDescription: 'Handcrafted full-grain leather briefcase with brass hardware for executives and creatives.',
    status: 'active',
    featured: true,
    isNew: false,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 42,
    createdAt: '2026-01-05T10:00:00.000Z',
    updatedAt: '2026-01-05T10:00:00.000Z',
  },
  {
    id: 'prod_2',
    name: 'Chronographe Automatique Calibre 40',
    slug: 'chronographe-automatique-calibre-40',
    sku: 'BG-WTC-040',
    description:
      'Engineered with an automatic mechanical movement with 48 hours of power reserve, the Calibre 40 features a 40mm 316L stainless steel case, an anti-reflective sapphire crystal face, and a sunray exhibition dial. Water-resistant to 50 meters, paired with a supple alligator-embossed leather band.',
    shortDescription: 'Swiss-movement mechanical automatic timepiece with exhibition caseback.',
    categoryId: 'cat_timepieces',
    brand: 'Baggio Horology',
    regularPrice: 890,
    salePrice: null,
    costPrice: 380,
    tax: 8.5,
    discount: 0,
    stockQuantity: 15,
    lowStockThreshold: 4,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_2_1',
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_2_2',
        url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var_2_1',
        name: 'Silver Sunburst / Black Leather',
        sku: 'BG-WTC-040-SLV',
        color: 'Silver / Black',
        size: '40mm',
        price: 890,
        stockQuantity: 9,
      },
      {
        id: 'var_2_2',
        name: 'Rose Gold / Dark Brown Leather',
        sku: 'BG-WTC-040-RGD',
        color: 'Rose Gold / Brown',
        size: '40mm',
        price: 940,
        stockQuantity: 6,
      },
    ],
    weight: 0.25,
    length: 10,
    width: 10,
    height: 8,
    seoTitle: 'Chronographe Automatique Calibre 40 | Baggio Horology',
    seoDescription: 'Automatic mechanical chronograph with sapphire glass and exhibition caseback.',
    status: 'active',
    featured: true,
    isNew: true,
    bestSeller: false,
    rating: 4.8,
    reviewCount: 19,
    createdAt: '2026-01-12T11:00:00.000Z',
    updatedAt: '2026-01-12T11:00:00.000Z',
  },
  {
    id: 'prod_3',
    name: 'Siena Blake-Stitched Chelsea Boots',
    slug: 'siena-blake-stitched-chelsea-boots',
    sku: 'BG-FOT-008',
    description:
      'Handcrafted in Tuscany by generational shoemakers, our Siena Chelsea Boots feature rich water-repellent suede uppers, durable Blake-stitched leather outsoles with anti-slip rubber inserts, and elasticated side gussets for effortless slip-on comfort.',
    shortDescription: 'Handmade Italian suede Chelsea boots with Blake welt construction.',
    categoryId: 'cat_footwear',
    brand: 'Baggio Calzature',
    regularPrice: 340,
    salePrice: 295,
    costPrice: 120,
    tax: 8.5,
    discount: 13,
    stockQuantity: 44,
    lowStockThreshold: 8,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_3_1',
        url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_3_2',
        url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var_3_1',
        name: 'Tobacco Suede / 42 EU',
        sku: 'BG-FOT-008-TOB-42',
        color: 'Tobacco Brown',
        size: '42 EU (9 US)',
        price: 295,
        stockQuantity: 15,
      },
      {
        id: 'var_3_2',
        name: 'Tobacco Suede / 43 EU',
        sku: 'BG-FOT-008-TOB-43',
        color: 'Tobacco Brown',
        size: '43 EU (10 US)',
        price: 295,
        stockQuantity: 18,
      },
      {
        id: 'var_3_3',
        name: 'Charcoal Suede / 42 EU',
        sku: 'BG-FOT-008-CHR-42',
        color: 'Charcoal Grey',
        size: '42 EU (9 US)',
        price: 295,
        stockQuantity: 11,
      },
    ],
    weight: 1.4,
    length: 34,
    width: 24,
    height: 14,
    seoTitle: 'Siena Italian Suede Chelsea Boots | Baggio',
    seoDescription: 'Blake-stitched Italian suede Chelsea boots with water-repellent finish.',
    status: 'active',
    featured: true,
    isNew: false,
    bestSeller: true,
    rating: 5.0,
    reviewCount: 38,
    createdAt: '2026-01-20T16:00:00.000Z',
    updatedAt: '2026-01-20T16:00:00.000Z',
  },
  {
    id: 'prod_4',
    name: 'Mongolian Pure Cashmere Overcoat',
    slug: 'mongolian-pure-cashmere-overcoat',
    sku: 'BG-APP-102',
    description:
      'Woven from 100% Grade-A Mongolian cashmere fiber with an ultra-soft handle and unmatched thermal insulation. Tailored with a clean notch lapel, horn buttons, dual welt pockets, and a back vent for ease of motion. Lined with breathable silk-cupro.',
    shortDescription: 'Luxurious double-faced cashmere overcoat tailored in timeless silhouette.',
    categoryId: 'cat_apparel',
    brand: 'Baggio Sartorial',
    regularPrice: 750,
    salePrice: null,
    costPrice: 310,
    tax: 8.5,
    discount: 0,
    stockQuantity: 18,
    lowStockThreshold: 4,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_4_1',
        url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_4_2',
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var_4_1',
        name: 'Camel / Medium (48)',
        sku: 'BG-APP-102-CAM-M',
        color: 'Camel Tan',
        size: 'Medium (48 EU)',
        price: 750,
        stockQuantity: 8,
      },
      {
        id: 'var_4_2',
        name: 'Camel / Large (50)',
        sku: 'BG-APP-102-CAM-L',
        color: 'Camel Tan',
        size: 'Large (50 EU)',
        price: 750,
        stockQuantity: 6,
      },
      {
        id: 'var_4_3',
        name: 'Onyx Black / Medium (48)',
        sku: 'BG-APP-102-BLK-M',
        color: 'Onyx Black',
        size: 'Medium (48 EU)',
        price: 750,
        stockQuantity: 4,
      },
    ],
    weight: 1.6,
    length: 60,
    width: 40,
    height: 8,
    seoTitle: 'Mongolian Pure Cashmere Overcoat | Baggio',
    seoDescription: 'Grade-A cashmere tailored overcoat for refined winter elegance.',
    status: 'active',
    featured: false,
    isNew: true,
    bestSeller: false,
    rating: 4.9,
    reviewCount: 14,
    createdAt: '2026-02-01T08:00:00.000Z',
    updatedAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'prod_5',
    name: 'Milano Polarized Acetate Sunglasses',
    slug: 'milano-polarized-acetate-sunglasses',
    sku: 'BG-ACC-015',
    description:
      'Hand-cut from premium Italian Mazzucchelli acetate with custom wire core temples and 5-barrel hinges. Fitted with Category 3 CR-39 polarized green lenses providing 100% UVA/UVB protection and crisp clarity.',
    shortDescription: 'Hand-sculpted Italian acetate sunglasses with polarized optical lenses.',
    categoryId: 'cat_accessories',
    brand: 'Baggio Ottica',
    regularPrice: 220,
    salePrice: 185,
    costPrice: 65,
    tax: 8.5,
    discount: 16,
    stockQuantity: 52,
    lowStockThreshold: 10,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_5_1',
        url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_5_2',
        url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var_5_1',
        name: 'Havana Tortoise / Classic Green',
        sku: 'BG-ACC-015-TOR',
        color: 'Havana Tortoise',
        size: '50-21-145',
        price: 185,
        stockQuantity: 30,
      },
      {
        id: 'var_5_2',
        name: 'Piano Black / Smoke Grey',
        sku: 'BG-ACC-015-BLK',
        color: 'Piano Black',
        size: '50-21-145',
        price: 185,
        stockQuantity: 22,
      },
    ],
    weight: 0.15,
    length: 16,
    width: 8,
    height: 6,
    seoTitle: 'Milano Polarized Acetate Sunglasses | Baggio',
    seoDescription: 'Handcrafted Italian acetate sunglasses with polarized lenses.',
    status: 'active',
    featured: true,
    isNew: false,
    bestSeller: true,
    rating: 4.7,
    reviewCount: 29,
    createdAt: '2026-02-05T12:00:00.000Z',
    updatedAt: '2026-02-05T12:00:00.000Z',
  },
  {
    id: 'prod_6',
    name: 'The Amalfi Weekender Leather Duffle',
    slug: 'amalfi-weekender-leather-duffle',
    sku: 'BG-LEA-032',
    description:
      'Engineered for 72-hour getaways. The Amalfi Duffle features rich full-grain calfskin leather, reinforced base studs, a separate ventilated shoe compartment, interior zippered organizer sleeves, and dual top carry handles.',
    shortDescription: 'Spacious full-grain leather duffle bag with designated footwear compartment.',
    categoryId: 'cat_leather',
    brand: 'Baggio Atelier',
    regularPrice: 560,
    salePrice: 495,
    costPrice: 220,
    tax: 8.5,
    discount: 11,
    stockQuantity: 19,
    lowStockThreshold: 5,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_6_1',
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
      {
        id: 'img_6_2',
        url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
        isPrimary: false,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        id: 'var_6_1',
        name: 'Vintage Tan / 45L',
        sku: 'BG-LEA-032-TAN',
        color: 'Vintage Tan',
        size: '45 Liters',
        price: 495,
        stockQuantity: 11,
      },
      {
        id: 'var_6_2',
        name: 'Espresso Brown / 45L',
        sku: 'BG-LEA-032-ESP',
        color: 'Espresso Brown',
        size: '45 Liters',
        price: 495,
        stockQuantity: 8,
      },
    ],
    weight: 2.3,
    length: 52,
    width: 28,
    height: 30,
    seoTitle: 'Amalfi Weekender Leather Duffle Bag | Baggio',
    seoDescription: 'Generous 45L travel duffle crafted with premium Italian full-grain leather.',
    status: 'active',
    featured: true,
    isNew: true,
    bestSeller: false,
    rating: 5.0,
    reviewCount: 22,
    createdAt: '2026-02-12T14:00:00.000Z',
    updatedAt: '2026-02-12T14:00:00.000Z',
  },
  {
    id: 'prod_7',
    name: 'Minimalist Bifold Card Wallet',
    slug: 'minimalist-bifold-card-wallet',
    sku: 'BG-LEA-077',
    description:
      'Ultra-slim profile crafted from unlined French Chevre goatskin. Houses up to 8 cards plus folded cash notes without creating pocket bulk. Hand-edged with wax paint.',
    shortDescription: 'Ultra-slim French Chevre leather bifold wallet with RFID protection.',
    categoryId: 'cat_leather',
    brand: 'Baggio Atelier',
    regularPrice: 110,
    salePrice: null,
    costPrice: 35,
    tax: 8.5,
    discount: 0,
    stockQuantity: 65,
    lowStockThreshold: 10,
    stockStatus: 'in_stock',
    images: [
      {
        id: 'img_7_1',
        url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    variants: [
      {
        id: 'var_7_1',
        name: 'Forest Green / Slim',
        sku: 'BG-LEA-077-GRN',
        color: 'Forest Green',
        size: 'Standard',
        price: 110,
        stockQuantity: 35,
      },
      {
        id: 'var_7_2',
        name: 'Classic Black / Slim',
        sku: 'BG-LEA-077-BLK',
        color: 'Classic Black',
        size: 'Standard',
        price: 110,
        stockQuantity: 30,
      },
    ],
    weight: 0.08,
    length: 10,
    width: 7.5,
    height: 1,
    seoTitle: 'Minimalist Bifold Leather Wallet | Baggio',
    seoDescription: 'Ultra-slim luxury leather card wallet with RFID protection.',
    status: 'active',
    featured: false,
    isNew: false,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 31,
    createdAt: '2026-02-14T09:00:00.000Z',
    updatedAt: '2026-02-14T09:00:00.000Z',
  },
  {
    id: 'prod_8',
    name: 'Aerolite Low-Top Court Sneaker',
    slug: 'aerolite-low-top-court-sneaker',
    sku: 'BG-FOT-021',
    description:
      'Minimalist court silhouette engineered with butter-soft nappa leather uppers, antibacterial calfskin lining, and an ultra-lightweight Margom rubber cupsole with memory foam insoles.',
    shortDescription: 'Crisp Italian nappa leather court sneakers with Margom rubber soles.',
    categoryId: 'cat_footwear',
    brand: 'Baggio Calzature',
    regularPrice: 260,
    salePrice: 220,
    costPrice: 95,
    tax: 8.5,
    discount: 15,
    stockQuantity: 3, // Low stock for testing low-stock alerts
    lowStockThreshold: 5,
    stockStatus: 'low_stock',
    images: [
      {
        id: 'img_8_1',
        url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    variants: [
      {
        id: 'var_8_1',
        name: 'Optic White / 42 EU',
        sku: 'BG-FOT-021-WHT-42',
        color: 'Optic White',
        size: '42 EU (9 US)',
        price: 220,
        stockQuantity: 2,
      },
      {
        id: 'var_8_2',
        name: 'Optic White / 43 EU',
        sku: 'BG-FOT-021-WHT-43',
        color: 'Optic White',
        size: '43 EU (10 US)',
        price: 220,
        stockQuantity: 1,
      },
    ],
    weight: 1.1,
    length: 32,
    width: 20,
    height: 12,
    seoTitle: 'Aerolite Low-Top Court Sneaker | Baggio',
    seoDescription: 'Premium Italian nappa leather white court sneakers with cushioned sole.',
    status: 'active',
    featured: false,
    isNew: true,
    bestSeller: false,
    rating: 4.6,
    reviewCount: 16,
    createdAt: '2026-02-18T10:00:00.000Z',
    updatedAt: '2026-02-18T10:00:00.000Z',
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban_hero_1',
    title: 'The Autumnal Heritage Collection',
    description: 'Sculpted in Florence. Crafted from vegetable-tanned full-grain leather, fine cashmere, and precision horology.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1600&auto=format&fit=crop',
    buttonText: 'Discover The Collection',
    buttonUrl: '/shop',
    type: 'hero',
    status: 'active',
    sortOrder: 1,
  },
  {
    id: 'ban_hero_2',
    title: 'Calibre 40 Automatic Horology',
    description: 'Swiss precision engineering meets understated elegance. Hand-assembled with exhibition sapphire crystal.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1600&auto=format&fit=crop',
    buttonText: 'Explore Timepieces',
    buttonUrl: '/category/luxury-timepieces',
    type: 'hero',
    status: 'active',
    sortOrder: 2,
  },
  {
    id: 'ban_promo_1',
    title: 'Artisanal Italian Leatherwork',
    description: 'Enjoy complimentary worldwide priority shipping and bespoke monogramming on orders over $150.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop',
    buttonText: 'Shop Leather Goods',
    buttonUrl: '/category/leather-goods',
    type: 'promo',
    status: 'active',
    sortOrder: 1,
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'cpn_welcome10',
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 100,
    maxDiscount: 100,
    startDate: '2026-01-01T00:00:00.000Z',
    expiryDate: '2027-12-31T23:59:59.000Z',
    usageLimit: 1000,
    usageCount: 24,
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cpn_baggio50',
    code: 'BAGGIO50',
    type: 'fixed',
    value: 50,
    minOrderAmount: 300,
    maxDiscount: 50,
    startDate: '2026-01-01T00:00:00.000Z',
    expiryDate: '2026-12-31T23:59:59.000Z',
    usageLimit: 200,
    usageCount: 15,
    status: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const initialStoreSettings: StoreSettings = {
  id: 'settings_default',
  storeName: 'Baggio',
  logo: '/baggio-logo.svg',
  email: 'concierge@baggio.com',
  phone: '+1 (800) 555-0199',
  address: '450 Via della Spiga, Milan / 742 Madison Ave, New York',
  currency: 'PKR',
  country: 'Pakistan',
  timezone: 'Asia/Karachi',
  shippingFee: 250,
  freeShippingThreshold: 5000,
  taxPercentage: 0,
  enableCod: true,
  cancellationRules: 'Orders may be cancelled within 12 hours of placement before entering processing status.',
};

export const initialReviews: Review[] = [
  {
    id: 'rev_1',
    productId: 'prod_1',
    userId: 'usr_cust_1',
    userName: 'Alexander Rossi',
    rating: 5,
    comment:
      'The leather craftsmanship on this Verona briefcase is peerless. Solid brass fittings, exquisite stitching, and it comfortably holds my 16" laptop plus portfolios.',
    status: 'approved',
    createdAt: '2026-02-02T11:20:00.000Z',
  },
  {
    id: 'rev_2',
    productId: 'prod_1',
    userId: 'usr_cust_2',
    userName: 'Sophia Laurent',
    rating: 5,
    comment:
      'Received it in 2 days. The aroma of vegetable-tanned leather when unboxing is incredible. Well worth every dollar.',
    status: 'approved',
    createdAt: '2026-02-18T14:45:00.000Z',
  },
  {
    id: 'rev_3',
    productId: 'prod_2',
    userId: 'usr_cust_1',
    userName: 'Alexander Rossi',
    rating: 5,
    comment:
      'Sublime sweep on the automatic movement. Wears slim under dress shirts and the alligator strap is exceptionally supple.',
    status: 'approved',
    createdAt: '2026-02-25T16:10:00.000Z',
  },
  {
    id: 'rev_4',
    productId: 'prod_3',
    userId: 'usr_cust_2',
    userName: 'Sophia Laurent',
    rating: 5,
    comment:
      'The Siena Chelsea boots required zero break-in period. The tobacco suede tone is deep and coordinates with everything.',
    status: 'approved',
    createdAt: '2026-03-01T10:05:00.000Z',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord_1001',
    orderNumber: 'BG-849102',
    userId: 'usr_cust_1',
    customerName: 'Alexander Rossi',
    email: 'customer@baggio.com',
    phone: '+1 (555) 234-5678',
    shippingAddress: {
      id: 'addr_1',
      userId: 'usr_cust_1',
      fullName: 'Alexander Rossi',
      phone: '+1 (555) 234-5678',
      address: '742 Evergreen Terrace, Apt 4B',
      city: 'Springfield',
      state: 'OR',
      postalCode: '97477',
      country: 'United States',
      isDefault: true,
    },
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'completed',
    orderStatus: 'Delivered',
    subtotal: 420,
    shippingFee: 0,
    discount: 10,
    tax: 34.85,
    total: 444.85,
    couponCode: 'WELCOME10',
    items: [
      {
        id: 'ord_item_1',
        productId: 'prod_1',
        variantId: 'var_1_1',
        productName: 'The Verona Executive Leather Briefcase',
        productImage: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1000&auto=format&fit=crop',
        variantName: 'Cognac Brown / Standard',
        quantity: 1,
        price: 420,
        subtotal: 420,
      },
    ],
    notes: 'Please ring bell upon arrival.',
    createdAt: '2026-02-10T11:30:00.000Z',
    updatedAt: '2026-02-14T15:00:00.000Z',
  },
  {
    id: 'ord_1002',
    orderNumber: 'BG-849103',
    userId: 'usr_cust_2',
    customerName: 'Sophia Laurent',
    email: 'sophia.laurent@example.com',
    phone: '+1 (555) 876-5432',
    shippingAddress: {
      id: 'addr_2',
      userId: 'usr_cust_2',
      fullName: 'Sophia Laurent',
      phone: '+1 (555) 876-5432',
      address: '88 Central Park West, Penthouse 12',
      city: 'New York',
      state: 'NY',
      postalCode: '10023',
      country: 'United States',
      isDefault: true,
    },
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'pending',
    orderStatus: 'Processing',
    subtotal: 480,
    shippingFee: 0,
    discount: 0,
    tax: 40.8,
    total: 520.8,
    items: [
      {
        id: 'ord_item_2',
        productId: 'prod_3',
        variantId: 'var_3_1',
        productName: 'Siena Blake-Stitched Chelsea Boots',
        productImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop',
        variantName: 'Tobacco Suede / 42 EU',
        quantity: 1,
        price: 295,
        subtotal: 295,
      },
      {
        id: 'ord_item_3',
        productId: 'prod_5',
        variantId: 'var_5_1',
        productName: 'Milano Polarized Acetate Sunglasses',
        productImage: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop',
        variantName: 'Havana Tortoise / Classic Green',
        quantity: 1,
        price: 185,
        subtotal: 185,
      },
    ],
    notes: 'Leave with doorman if unavailable.',
    createdAt: '2026-03-08T09:15:00.000Z',
    updatedAt: '2026-03-08T09:20:00.000Z',
  },
];
